# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# Please consult the lectures
#Vectors are strictly 1-dimentional array
#Matrices are 2-dimentional (Matrix can still have only one row or one column)

**2. How to import `NumPy` library?**

In [2]:
# To avoid overwriting the output, please code here
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [3]:
list_1 = [1,2,3,4,5]

In [4]:
# To avoid overwriting the output, please code here
np_arr=np.array(list_1)
np_arr,type(np_arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [5]:
# To avoid overwriting the output, please code here
np_arr = np.arange(6)
np_arr

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [6]:
# To avoid overwriting the output, please code here
z_arr = np.zeros(5)
z_arr

array([0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [7]:
# To avoid overwriting the output, please code here
z_arr = np.zeros((3,4))
z_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [8]:
# To avoid overwriting the output, please code here
ones_arr = np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [9]:
# To avoid overwriting the output, please code here
tens_arr = np.ones(5)*10
tens_arr

array([10., 10., 10., 10., 10.])

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [10]:
# To avoid overwriting the output, please code here
even_num = np.arange(52,100, 2)
even_num

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [11]:
# To avoid overwriting the output, please code here
arr = np.linspace(0,1,10, retstep=True)
arr

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [12]:
# To avoid overwriting the output, please code here
v_arr = np.arange(25)
v_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
# To avoid overwriting the output, please code here
v_arr1 = v_arr.reshape(5,5)
v_arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
# To avoid overwriting the output, please code here
v_arr.shape = (5,5)
v_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [15]:
# To avoid overwriting the output, please code here
matx = np.arange(0.1 ,2.6, 0.1)
matx
matx = matx.reshape(5,5)
matx

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [16]:
# To avoid overwriting the output, please code here
new_matx = np.linspace(0, 24, 25, dtype = int).reshape(5,5)
#new_matx
print(new_matx)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [17]:
# Please consult the lectures.
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [18]:
# To avoid overwriting the output, please code here
rand_int = np.random.randint(10)
rand_int

5

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [19]:
# To avoid overwriting the output, please code here
rand_num = np.random.rand(7,5)
print(rand_num)

[[0.14306505 0.04338639 0.04637606 0.99170906 0.14006207]
 [0.17378576 0.67539412 0.52031361 0.79103365 0.71192605]
 [0.06586126 0.0212819  0.01730119 0.59631919 0.99737304]
 [0.2255145  0.33173427 0.55131523 0.15129988 0.41811683]
 [0.67360118 0.48191314 0.83584561 0.72232666 0.7976754 ]
 [0.41139907 0.93652751 0.88923076 0.19627501 0.65019184]
 [0.10078468 0.43130796 0.20248213 0.53367282 0.20087511]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [20]:
# To avoid overwriting the output, please code here
iden_matx = np.identity(5)*5
iden_matx

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck